### ISSUE TITLE
Segmentation fault when running graphtyper call

### ISSUE THREAD

**Issue by ivargr** [DecodeGenetics/graphtyper#18]
Hi,

I've been following the instructions in the Readme for creating a graph, indexing it and running graphtyper call, but I always end up getting `segmentation fault` after running graphtyper call. I've made a small test case that should be reproducible that always ends up with segmentation fault using [this small fasta file](http://folk.uio.no/ivargry/graphtyper_testdata/test.fa) and [this sam file](wget http://folk.uio.no/ivargry/graphtyper_testdata/test.sam). 

```
wget http://folk.uio.no/ivargry/graphtyper_testdata/test.fa
wget http://folk.uio.no/ivargry/graphtyper_testdata/test.sam

samtools faidx test.fa
graphtyper construct testgraph test.fa 21:1-1,000,000
graphtyper index testgraph
graphtyper call testgraph --sam test.sam 21:1-1,000,000
```

My guess is that I am using graphtyper wrongly, but I am not able to see how. Have I misunderstood how to run graphtyper? I note that my fasta file has chromosome name "21" and not "chr21", thus I specify `21:1-1000000` when running the commands, but I guess that shouldn't matter?

I am using version 1.4 (50d2a57), but experience the same also when using version 2.0.

Any help is appreciated!

**Comment by hannespetur** [comment]
Hello,

thank you for posting your issue. First, I'd like to note that I highly recommend using the [GraphTyper pipelines](https://github.com/DecodeGenetics/graphtyper-pipelines) when running GraphTyper. GraphTyper is designed such that every step is in a different subcommand, this makes it very customizable but also complicated to run.

To answer your question, you should use 21 as it is in your FASTA file (chr21 won't work). I could reproduce the problem, thank you for providing the data to test on. The problem occurs when GraphTyper attempts to seek to position 21:1-1,000,000 in the SAM and fails because there is no index available. To fix this you can sort the reads by position, convert SAM->BAM and index the BAM.

```sh
wget https://github.com/DecodeGenetics/graphtyper/releases/download/v2.0-beta/graphtyper
chmod a+x graphtyper

wget http://folk.uio.no/ivargry/graphtyper_testdata/test.fa
wget http://folk.uio.no/ivargry/graphtyper_testdata/test.sam

samtools faidx test.fa
./graphtyper construct testgraph test.fa 21:1-1,000,000
./graphtyper index testgraph

# Added steps
samtools sort test.sam -o test.sorted.bam
samtools index test.sorted.bam
./graphtyper call testgraph --sam test.sorted.bam 21:1-1,000,000
```

Alternatively, you can tell graphtyper not to seek by using a dot '.' as region.

```sh
./graphtyper call testgraph --sam test.sam . # Region is .
```

However, this will align all reads in the test.sam to your 21:1-1,000,000 graph, which may not be what you want. In either case, the resulting VCFs are empty because the region 21:1-1,000,000 consists only of Ns and thus has no reads align there.

I will add a message in future releases when this problem occurs as Graphtyper should clearly output a more user-friendly error message, so thank you very much for posting.


Best,
Hannes

**Comment by ivargr** [comment]
Thank you very much for the explanation and solution, sorting and indexing the sam/bam solves the problem! :)

**Comment by hannespetur** [comment]
Great. GraphTyper now outputs a nicer message when a region is specified without an index.
