### ISSUE TITLE
Run full genotype pipeline with input vcf

### ISSUE THREAD

**Issue by hannespetur** [DecodeGenetics/graphtyper#27]
When the `genotype --vcf` option is used then GraphTyper genotypes only using a graph created based on that VCF. Another important usecase is to also run the "normal" genotyping pipeline (with discovery) using an input VCF. Suggested in #25 .

**Comment by hannespetur** [comment]
Added in version 2.2. See https://github.com/DecodeGenetics/graphtyper/releases/tag/v2.2

**Comment by brentp** [comment]
thank you. giving this a try now, but seem the cluster queue is quite backed up.

**Comment by marqueda** [comment]
Dear Hannes,
Would it be possible or make sense to implement this enhancement also for genotype_sv, so that the latter could discover also SNPs and small SVs and genotype them together with the large SVs from Manta? Or would there be a cheap way to tweak the graphtyper genotype command to run with the genotype_sv parameters and use the Manta SVs as prior_vcf? It would of course be elegant if all types of variants could be graph-aligned and called in a single run.
Best, David

**Comment by hannespetur** [comment]
Thanks David, that makes sense. You can genotype small variants and SVs together by:

 1. Run 'genotype' on your samples (Run 1)
 2. Concatenate all variants discovered small variants from results/input_sites/ and merge with Manta's SV VCF
 3. Run 'genotype_sv' on your samples with both small variants and SVs as input (Run 2).

however this is a two run solution and I agree that an one run solution would be more elegant. I think it should be possible to implement that by combining these three steps on a region basis but I will need to look a bit better into it.

Best,
Hannes

**Comment by marqueda** [comment]
Dear Hannes,
Thank you for your help with this. It would indeed be great to be able to do that in one run in the future, as in the end, most people will probably like to call all types of variation at the same time - that would be a great enhancement!
Best,
David
