### ISSUE TITLE
genotype with >1 VCF input file

### ISSUE THREAD

**Issue by martinghunt** [DecodeGenetics/graphtyper#39]
I'm working on bacteria. My use case is that I have more than one VCF file, made with different tools on the same sample and ref genome. They contain calls that conflict with each other (eg REF=A, tool 1 says ALT=G, tool2 says ALT=AT). Is it possible to use VCFs like this as input to graphtyper, so it makes a graph of all the variants and then genotypes? Or wondering if I can cat them (and then sort/bgzip/index) and use that in the `--vcf` option of `graphtyper genotype`?

**Comment by hannespetur** [comment]
Hello,

Yes I think this should work if you create one VCF, e.g.

```sh
bcftools concat <A.vcf.gz> <B.vcf.gz> ... | bcftools sort -Oz -o all.vcf.gz -
tabix all.vcf.gz
graphtyper genotype <REF.fa> --vcf=all.vcf.gz --sams=<bamlist> --region_file=<region_file>
```

graphtyper should automatically remove the duplicate variants in the VCF before creating the graph. Also if your VCF files are large you could first remove all the genotype calls e.g. with `bcftools view --drop-genotypes <VCF>` because graphtyper only uses the variant site information. 

Best,
Hannes

**Comment by martinghunt** [comment]
Thanks for the fast reply! That's great, I'll give it a go.

Best wishes,
Martin
