### ISSUE TITLE
Call population SVs and Genotype

### ISSUE THREAD

**Issue by biozzq** [DecodeGenetics/graphtyper#42]
Dear @hannespetur 

Thank you for this nice tool. I have some questions about how to process the population short sequencing data. My plan like following. Hope you can give me some suggestions. Thank you.

1, for each sample, I will use 3 independent tools to call SVs: Delly, Lumpy and Manta. 

2, I will filter for SVs passing the quality filters suggested by DELLY, Lumpy and Manta (flag PASS). 

3, only SVs called by at least 2 of the 3 tools were retained. Here, I do not know if `svimmer` can realize this process? I know SURVIVOR can, but its output can not be as input for `graphtyper`.

Through above processes, I will get one intergrated VCF file for each sample.

4, Using `svimmer` to merge the intergrated VCF across different samples into a single VCF file for this population data.

5, Genotype the SVs for this population using `graphtyper` with `--sams all.bam.list` and `svimmer merged VCF file`.

From NC publication (https://doi.org/10.1038/s41467-019-13341-9), I found you only used Manta to call SVs and kept all the variants including those that did not pass in Manta's filter. I do not if my plan can work fine.

Sincerely.
Zhuqing

**Comment by hannespetur** [comment]
Hello, you could try the following with svimmer:

a. Run svimmer on each individual filtered file of DELLY, Lumpy, Manta (to merge nearby SVs in one).
b. For each individual, run svimmer on all three output files of previous step and filter that VCF with `bcftools view --include "INFO/NUM_MERGED_SVS>1"`. Because we made sure that all nearby SVs within a tool had been merged it should mean that at least 2 of those tools called the SV.
c. Run svimmer on the outputs of the previous step for every individual.

Try it out and test if the output of step b) is valid and let me know how it goes. I feel like it should be easy enough to have an option to add an INFO field with number of unique file IDs in svimmer which could really guarantee two tools did call the SV.


Best,
Hannes

**Comment by biozzq** [comment]
Dear @hannespetur 

Thank you. I tried a&b in one sample. From the screen output, I do not know why it always gave me warnings like following as I have filtered out the SVs had a length <50bp.
![image](https://user-images.githubusercontent.com/15704257/85350162-ef89d000-b532-11ea-949a-61eb4eddb5ca.png)

Also, some SVs repeat three or more times in the outout from graphtyper (following screenshot), does it mean different qualitative evaluations, e.g., breakponts, coverage, and the aggregation of breakpoints and coverage? I saw different evaluations may have different FILTER flags, thus how can I filter them to get a relatively accurate set of variants and their genotypes.
![image](https://user-images.githubusercontent.com/15704257/85357131-3c75a280-b543-11ea-9600-64a525378cff.png)

More, sometimes I found the FILTER flag is "PASS" but the FT flag is "FAILN" for one variant. According to your NC publication, if we filtered by FT, we can reduce the false positives; however, at the same time we lose many true positives. If for you, how will you balance this quality control.

Last, I found that graphtyper only uses the variant site information (https://github.com/DecodeGenetics/graphtyper/issues/39#issuecomment-636045812), thus, I am very curious about why we can not use SURVIVOR to merge SVs although SURVIVOR replaced the original INFO field of the VCF when merging.

Sincerely,
Zhuqing

**Comment by hannespetur** [comment]
Hello, can you send me examples of the VCF records withs the SVs which are considered <50bp?

> Also, some SVs repeat three or more times in the outout from graphtyper (following screenshot), does it mean different qualitative evaluations, e.g., breakponts, coverage, and the aggregation of breakpoints and coverage?

Correct. If you want a single SV use the aggregated one (which is what we used in the paper).

> I saw different evaluations may have different FILTER flags, thus how can I filter them to get a relatively accurate set of variants and their genotypes.

The FILTER field is set by graphtyper if it's confident in SV but the FT format field is per sample for each call of the SV. Require that both are PASS if you want a accurate set of variants and calls.

> Last, I found that graphtyper only uses the variant site information, thus, I am very curious about why we can not use SURVIVOR to merge SVs although SURVIVOR replaced the original INFO field of the VCF when merging.

Yes, graphtyper uses many of the values in the INFO field SURVIVOR replace, like SVINSSEQ which contains the inserted sequence at the SV site. If the SVINSSEQ is missing, graphtyper will incorrectly think there is no inserted sequence and thus the breakpoint sequence will be wrong. As far as I know, only Manta will output this info which is why we decided to use the manta+graphtyper pipeline in our paper.

Best,
Hannes

**Comment by biozzq** [comment]
Dear @hannespetur 

Many thanks for the prompt reply. I have attached the VCF file that generate these warnings. I think you can trace above ignored variants in this VCF file.
[ZJ117.vcf.gz](https://github.com/DecodeGenetics/graphtyper/files/4819540/ZJ117.vcf.gz)

If I only focus on the deletion and duplication but not insertion, can I use SURVIVOR to merge?

Sincerely,
zhuqing

**Comment by hannespetur** [comment]
graphtyper is not parsing correctly the delly SVs because they have no SVLEN specified in the INFO field. Graphtyper uses this info field to learn the size of the SV. I see there is a INFO/END specified so I suppose graphtyper could assume that SVLEN=INFO/END-POS to handle this situation.

> If I only focus on the deletion and duplication but not insertion, can I use SURVIVOR to merge?
No, deletion and duplications often have a small piece of DNA inserted at the SV breakpoint site kept in the INFO/SVINSSEQ field of Manta VCFs. Without this information the breakpoint will be inaccurate.

Best,
Hannes

**Comment by biozzq** [comment]
Dear @hannespetur 

Thank you. do you mean that the VCF file used as input for graphtyper should be generated by Manta, because both Lumpy and delly will not report the INFO/SVINSSEQ field? More, the long reads software (minmap2 & sniffles) also does not report these information. If that is the case, I'm a little overwhelmed about how to use graphtyper better.

In my study, most samples are sequenced using the short reads and only four samples with pacbio long reads. I plan to do SVs discovery first, and then generate a uniform SV set, and do the genotype finally. In my mind, I would use different software to do SVs discovery to reduce the false positive and use graphtyper to do the genotype. Can you give me some suggestions on SVs discovery and merge in order to be compatible with graphtyper? Thank you.

Sincerely,
zhuqing

**Comment by hannespetur** [comment]
Hey, sorry I don't mean to be overwhelming - I am just trying to bring some awareness to the limitations in graphtyper to improve your experience.

Our best practice recommendation is to use the pipeline we describe in our paper (Manta+svimmer+graphtyper). If you want to utilize Lumpy and delly to reduce false positives, here is my suggestion:

1. Per sample, run Manta, DELLY and Lumpy.
2. Per sample, join Manta variants to Delly and Lumpy variants using svimmer and keep only variants that were also found by delly or lumpy:
```sh
svimmer --join-mode <(echo "${sample.manta}.vcf.gz"; echo "${sample.delly}.vcf.gz"; ${sample.lumpy}.vcf.gz) chr{1..22} | bcftools view -i "INFO/NUM_JOINED_SVS > 1" -Oz -o ${sample.out}.vcf.gz
tabix -p vcf ${sample.out}.vcf.gz
```
Be sure that the Manta VCF is the first VCF file.

3. For the whole population, merge all sample VCFs using svimmer
```sh
ls sample_vcf/*.vcf.gz > vcf_list
svimmer vcf_list chr{1..22} | bgzip -c > merged.vcf.gz
tabix -p vcf merged.vcf.gz
```

4. Genotype with graphtyper
```sh
graphtyper genotype_sv ${REF.FA} merged.vcf.gz --sams=${bamlist} --region=${region} --threads=${threads}
```

Best,
Hannes

**Comment by biozzq** [comment]
Dear @hannespetur 

Thank you. Very nice that you can share me your idea. Hope graphtyper will get more and more appreciated.

Sincerely,
Zhuqing

**Comment by koujiaodahan** [comment]
Hi,which manata output vcf will be merged by svimmer as the input of graphtyper?diploidSV.vcf.gz or candidateSV.vcf.gz or candidateSmallIndels.vcf.gz or All the three?

**Comment by biozzq** [comment]
Hi @koujiaodahan 

I usually use the diploidSV.vcf.gz.

Best,

**Comment by vitty0513** [comment]
> 

Hi dear,
I used 3 software to call SVs and then use svimmer to merge, however, I found some INFO/NUM_MERGED_SVS>3. It should not great than 3 as we only used 3 methods. 
![image](https://github.com/DecodeGenetics/graphtyper/assets/58814051/fd8b15a2-b468-496e-89ad-32b33fdb388e)
 Many thanks!
