### ISSUE TITLE
Support for .csi indexed vcfs

### ISSUE THREAD

**Issue by MaximilianStammnitz** [DecodeGenetics/graphtyper#43]
Hi Hannes,

Relating to [svimmer #2](https://github.com/DecodeGenetics/svimmer/issues/2): when genotyping SVs with at least one breakpoint reaching into a chromosome segment > 512Mb, Graphtyper currently stops and raises the following error:

[E::hts_idx_check_range] Region 283784..714781126 cannot be stored in a tbi index. Try using a csi index with min_shift = 14, n_lvls >= 6
[2020-06-26 12:04:41.161796] <warning> vcf.cpp:1191 Could not build VCF index
cp: cannot stat '/tmp/graphtyper_200626_120435_1_000280000.7yzvuk/graphtyper.vcf.gz.tbi': No such file or directory

So it looks like the first task lies in tailoring the Vcf::write_tbi_index() function in [vcf.cpp](https://github.com/DecodeGenetics/graphtyper/blob/master/src/typer/vcf.cpp) towards a .csi output.

You mentioned that the main challenge overall lies in Graphtyper's current use of a cpp VCF library which doesn't support CSI indeces, could you please point me to this? Happy to get in touch with our team's cpp experts, and can also share the test data with you.

Many thanks,
Max

**Comment by hannespetur** [comment]
Wait a minute, that error is for building the VCF index not in the read phase.. are you able to read a VCF file with a csi index using graphtyper? It didn't work for me when I tested it. I am using a fork of seqan to read in VCF (seqanHTS) in the graph construction phase and when I looked at the code for it I thought I only saw code for querying a tbi index.

It should be much less of a problem for me to add building csi index since I am using htslib for that.

Best,
Hannes

**Comment by MaximilianStammnitz** [comment]
Ah, that's great news. Yes - Graphtyper appears to seemlessly read the original gzipped vcf with a .csi index!

**Comment by hannespetur** [comment]
Nice! Thanks, I will post a message here when I have the building of a csi index ready.

**Comment by MaximilianStammnitz** [comment]
Many thanks Hannes, let me know if/when you'd like me to test any sets.

**Comment by hannespetur** [comment]
Hello, I have added an advanced option for writing csi index (`--csi`). Could you please test it on your end? I can make a static build with the changes if you want. Also, sorry for the delay - some problems arose at work which I had to take care of first.

On a related note, I have yet not been able to read csi index with graphtyper. How are you creating the csi indices which graphtyper is reading?

Best,
Hannes

**Comment by MaximilianStammnitz** [comment]
Hi @hannespetur, many thanks for picking up on this issue - no worries at all with respect to the delay, fully understand.

Regarding the reading of csi-indexed VCFs with GraphTyper2: from memory, the program somehow crashed in only one of the two verbose modes (I think it was --vverbose, however not in --verbose), I remember being rather surprised by that, but haven't been able to follow up on this at all ...

... aiming to test your dev branch over this weekend, and will provide you with a detailed summary.

Best,
Max

**Comment by MaximilianStammnitz** [comment]
Hi again @hannespetur - to speed things up a little, would you mind sharing a binary version of this [--csi branch](https://github.com/DecodeGenetics/graphtyper/tree/write_csi) with me? Feel free to mail at mrs72[AT]cam.ac.uk
Cheers, M

**Comment by hannespetur** [comment]
Hey, I am out of office until August 4th - I will be in touch then. Best, Hannes

**Comment by hannespetur** [comment]
Thanks for your patience @MaximilianStammnitz . I found out that reading csi index fails in debug mode but the error was not captured in release mode - that's why I couldn't get it the csi reading to work for on my end before, since I was running on a debug build.

Good news is that I have now finished implementing the csi reading, could you verify that this graphtyper binary works on your end?
https://www.dropbox.com/s/5im1ta8t77b3ck2/graphtyper?dl=0

csi reading should be used if a <file>.vcf.gz.csi is found, but writing a csi index requires the advanced `--csi` option.

Best,
Hannes

**Comment by MaximilianStammnitz** [comment]
Hi @hannespetur, thanks for getting right back to this problem after your return. I will have a look at the new version now and get back to you!

**Comment by MaximilianStammnitz** [comment]
Dear @hannespetur,

Thanks a million for your continuous support and for the fix! The new --csi option runs very ysmoothly, and I am happy to confirm that the performance is now stable on +512 Mb chromosomes. 🥇 

... on the other hand, I feel like a terrible pain to you, because going quite keenly through my first outputs I think I've already spotted a (likely rather small) issue with respect to certain genotypings ... will open another thread tomorrow if you don't mind!

All the best,
Max

**Comment by hannespetur** [comment]
No problem. Of course, feel free to open a new thread.

Best,
Hannes
