### ISSUE TITLE
Graphtyper appropriate for low-coverage data (1x) ?

### ISSUE THREAD

**Issue by clairemerot** [DecodeGenetics/graphtyper#50]
I am studying SVs in non-model species and interested to analyze SV at populations- scale, hence to be able to genotype a large number of individuals (~1000-2000). Contrary to humans, to have a lot of whole-genome samples we usually save money by working at low coverage (1-2x). To work on SNPs, this is good because more and more tools use genotype likelihoods. But I fail to find the equivalent for SV. Yet, Graphtyper strikes me as the kind of tools that work for that purpose and be more widely used in non-model species or ecological studies! 

Do you think it can leverage the power to have large sample sizes to catalog and genotype SV, even if certainty at the individual level is poor due to shallow-coverage? Have you tried to apply this Graphtyper to low-coverage data (1-2x)? Do you think it would perform well or is it too risky? If I proceed to do so on my data, do you have specific recommendations to account for such a shallow coverage? Are you aware of other studies or methods that have done so?

Thanks a lot for your help and attention
Claire

**Comment by hannespetur** [comment]
Hello Claire,

I expect it will be challenging to discover/generate an set of input SVs for non-model species with such a low coverage. Our recommended pipeline is to use Manta to discover SVs but I haven't tried running Manta with low coverage data and I do not expect it to perform well with shallow coverage. For humans this is less of an issue because there are large catalogs of known SVs which could be used as input.

But if you can overcome that issue I would think graphtyper could call the SVs reasonably well - at least when calling deletions and duplications. In supplementary figure 5 of our [GraphTyper2 puplication](https://www.nature.com/articles/s41467-019-13341-9) we experimented with calling deletions at different input coverages and the results were better than I had anticipated, particularly for the graphtyper coverage model. 

I am not aware of other studies focusing using low coverage data.


Best,
Hannes
