### ISSUE TITLE
genotype_sv  [W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported

### ISSUE THREAD

**Issue by koujiaodahan** [DecodeGenetics/graphtyper#57]
hi: my jo
$graphtyper genotype_sv /zfssz2/ST_MCHRI/BIGDATA/USER/lizhichao/cnvnator/testdata/hg38/Homo_sapiens_assembly38.fasta merged.vcf.gz --sams=test_svimmer.list --region_file=/zfssz2/ST_MCHRI/BIGDATA/USER/lizhichao/cnvnator/software/svimmer/region_file
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported
[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/6aef897c3d6ff0c78aff06ac189178dd": Protocol not supported

**Comment by hannespetur** [comment]
Hello,

it can't find the reference sequence cache to decode your CRAMs. This functionality is handled by htslib which the environment variables REF_CACHE and REF_PATH for this purpose, see more: http://www.htslib.org/doc/samtools.html#ENVIRONMENT_VARIABLES

If you do not have sequence cache you will need to run misc/seq_cache_populate.pl which is provided along the distribution of Samtools. In the next release of graphtyper I hope to be able to use the input reference to decode CRAMs within `genotype_sv` - but my suggestion will still be recommended since it has a faster CRAM decoding speed.

Best,
Hannes

**Comment by bw2** [comment]
For anyone else that runs into this issue, the following worked for me:

```
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai 
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.ref_cache.tar.gz

tar xzf Homo_sapiens_assembly38.ref_cache.tar.gz
export REF_PATH="$(pwd)/ref/cache/%2s/%2s/%s:http://www.ebi.ac.uk/ena/cram/md5/%s"
export REF_CACHE="$(pwd)/ref/cache/%2s/%2s/%s"

...

{command that was generating the '[W::find_file_url] Failed to open reference..' error}
```
